// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhLQ1Ulp1VAtqDtiOnu8UuRN17-_tJVR4',
    appId: '1:373150411941:web:50400c090c526ffd3f714c',
    messagingSenderId: '373150411941',
    projectId: 'todofirebase-3f701',
    authDomain: 'todofirebase-3f701.firebaseapp.com',
    storageBucket: 'todofirebase-3f701.appspot.com',
    measurementId: 'G-59GJTSQ855',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBshKf0ypQWMhpv_nLuDb_oZlIGjk4NB-c',
    appId: '1:373150411941:android:ba923c792fe27fa23f714c',
    messagingSenderId: '373150411941',
    projectId: 'todofirebase-3f701',
    storageBucket: 'todofirebase-3f701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWZA4iUs78z4R4V-k5RTJyN6B0nOyPFIQ',
    appId: '1:373150411941:ios:d7b2f803212a00013f714c',
    messagingSenderId: '373150411941',
    projectId: 'todofirebase-3f701',
    storageBucket: 'todofirebase-3f701.appspot.com',
    iosClientId: '373150411941-a1kuir1o8s70h8v2tkjh0rol8mfe103e.apps.googleusercontent.com',
    iosBundleId: 'com.example.todofirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWZA4iUs78z4R4V-k5RTJyN6B0nOyPFIQ',
    appId: '1:373150411941:ios:87fded2ab7bbea8c3f714c',
    messagingSenderId: '373150411941',
    projectId: 'todofirebase-3f701',
    storageBucket: 'todofirebase-3f701.appspot.com',
    iosClientId: '373150411941-6usj3e2079ncj1ofhshsrasmnvs11euh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todofirebase.RunnerTests',
  );
}
