// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALbrFiWtJUOAbeixsVZXviKwH0Pn73F-0',
    appId: '1:888564234949:web:5ad2dffd3ff64852460eac',
    messagingSenderId: '888564234949',
    projectId: 'fir-series-34fed',
    authDomain: 'fir-series-34fed.firebaseapp.com',
    storageBucket: 'fir-series-34fed.appspot.com',
    measurementId: 'G-B0NZTBKJPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjJoCZ49i3e_4IVggGyTAzSuQ11H7CfEs',
    appId: '1:888564234949:android:26edb3cc7b5a08dc460eac',
    messagingSenderId: '888564234949',
    projectId: 'fir-series-34fed',
    storageBucket: 'fir-series-34fed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6KGLaO8c2FvVpiXPeAEAVGessVqsFe0I',
    appId: '1:888564234949:ios:eb0275151abfa624460eac',
    messagingSenderId: '888564234949',
    projectId: 'fir-series-34fed',
    storageBucket: 'fir-series-34fed.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6KGLaO8c2FvVpiXPeAEAVGessVqsFe0I',
    appId: '1:888564234949:ios:9772b62fe906f5a4460eac',
    messagingSenderId: '888564234949',
    projectId: 'fir-series-34fed',
    storageBucket: 'fir-series-34fed.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
